# PYTHIA configuration file.
# Generated on Wed Sep 9 20:54:24 CDT 2020 with the user supplied options:
# --with-hepmc2=/uscms/home/etuecke/nobackup/darkPhotonsBranchingRatios/hepMC2/cleanDIR/hepmc/install

# Install directory prefixes.
PREFIX_BIN=/uscms/home/etuecke/nobackup/darkPhotonsBranchingRatios/pythia_forBranchingRatios/pythia8235/bin
PREFIX_INCLUDE=/uscms/home/etuecke/nobackup/darkPhotonsBranchingRatios/pythia_forBranchingRatios/pythia8235/include
PREFIX_LIB=/uscms/home/etuecke/nobackup/darkPhotonsBranchingRatios/pythia_forBranchingRatios/pythia8235/lib
PREFIX_SHARE=/uscms/home/etuecke/nobackup/darkPhotonsBranchingRatios/pythia_forBranchingRatios/pythia8235/share/Pythia8

# Compilation flags (see ./configure --help for further documentation).
ENABLE_SHARED=false
CXX=g++
CXX_COMMON=-O2  -pedantic -W -Wall -Wshadow -fPIC
CXX_SHARED=-shared
CXX_SONAME=-Wl,-soname,
LIB_SUFFIX=.so

# EVTGEN configuration.
EVTGEN_USE=false
EVTGEN_BIN=
EVTGEN_INCLUDE=./
EVTGEN_LIB=./

# FASTJET3 configuration.
FASTJET3_USE=false
FASTJET3_BIN=
FASTJET3_INCLUDE=./
FASTJET3_LIB=./

# HEPMC2 configuration.
HEPMC2_USE=true
HEPMC2_BIN=/uscms/home/etuecke/nobackup/darkPhotonsBranchingRatios/hepMC2/cleanDIR/hepmc/install/bin/
HEPMC2_INCLUDE=/uscms/home/etuecke/nobackup/darkPhotonsBranchingRatios/hepMC2/cleanDIR/hepmc/install/include
HEPMC2_LIB=/uscms/home/etuecke/nobackup/darkPhotonsBranchingRatios/hepMC2/cleanDIR/hepmc/install/lib

# HEPMC3 configuration.
HEPMC3_USE=false
HEPMC3_BIN=
HEPMC3_INCLUDE=./
HEPMC3_LIB=./

# LHAPDF5 configuration.
LHAPDF5_USE=false
LHAPDF5_BIN=
LHAPDF5_INCLUDE=./
LHAPDF5_LIB=./

# LHAPDF6 configuration.
LHAPDF6_USE=false
LHAPDF6_BIN=
LHAPDF6_INCLUDE=./
LHAPDF6_LIB=./

# POWHEG configuration.
POWHEG_USE=false
POWHEG_BIN=
POWHEG_INCLUDE=./
POWHEG_LIB=./

# PROMC configuration.
PROMC_USE=false
PROMC_BIN=
PROMC_INCLUDE=./
PROMC_LIB=./

# ROOT configuration.
ROOT_USE=false
ROOT_BIN=
ROOT_INCLUDE=./
ROOT_LIB=./

# GZIP configuration.
GZIP_USE=false
GZIP_BIN=
GZIP_INCLUDE=./
GZIP_LIB=./

# BOOST configuration.
BOOST_USE=false
BOOST_BIN=
BOOST_INCLUDE=./
BOOST_LIB=./

# PYTHON configuration.
PYTHON_USE=false
PYTHON_BIN=
PYTHON_INCLUDE=./
PYTHON_LIB=./
